version: "3.6"

services:
  mailhog:
    container_name: mailhog.pedalwithpete
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - ho_apps
      - pwp_net

  adminer:
    container_name: adminer.pedalwithpete
    image: adminer
    ports:
      - 28081:8080
    networks:
      - pwp_net
    depends_on:
      - mysql8

  mysql8:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql8.pedalwithpete
    # Serves as a surrougate trigger for initializing the db: https://hub.docker.com/_/mysql?tab=description#usage-against-an-existing-database
    environment:
      MYSQL_ROOT_PASSWORD: ${PWP_DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql8/db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    networks:
      - pwp_net

  wordpress:
    image: wordpress:6.1-php7.4-apache
    container_name: wp.pedal_with_pete
    environment:
      WORDPRESS_DB_HOST: mysql8.pedalwithpete
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${PWP_DB_PASSWORD}
      WORDPRESS_DB_NAME: PedalWithPete # create new schema with utf8mb4_bin
      WORDPRESS_DEBUG: 1
    restart: unless-stopped
    ports:
      - 28080:80
    volumes:
      - ./app/wordpress:/var/www/html
    depends_on:
      - mysql8
    networks:
      - pwp_net

  # # Bitnami Wordpress
  # wordpress:
  #   image: bitnami/wordpress:latest
  #   container_name: wp.pedal_with_pete
  #   environment:
  #     # Documentation: https://hub.docker.com/r/bitnami/wordpress
  #     MARIADB_HOST: mysql8.pedalwithpete
  #     MARIADB_PORT_NUMBER: 3306
  #     # WORDPRESS_DATABASE_NAME: PedalWithPete
  #     WORDPRESS_DATABASE_USER: root
  #     WORDPRESS_DATABASE_PASSWORD: ${PWP_DB_PASSWORD}
  #     # WORDPRESS_SKIP_INSTALL: "yes"
  #     # This prompts seeking apache config file at /opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf
  #     # WORDPRESS_ENABLE_HTACCESS_PERSISTENCE: "yes"
  #     # Site config
  #     WORDPRESS_USERNAME: admin
  #     WORDPRESS_PASSWORD: Test1234
  #     WORDPRESS_EMAIL: pwp@mailhog
  #     WORDPRESS_BLOG_NAME: "Sandbox :: Pedal With Pete"
  #     WORDPRESS_SCHEME: http
  #     # Mail configurations
  #     SMTP_HOST: 127.0.0.1
  #     SMTP_PORT: 1025
  #     SMTP_USER: pwp@mailhog
  #     SMTP_PASSWORD: null
  #     # SMTP_PROTOCOL: none # [tls, ssl, none]
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     # - ./conf.d:/bitnami/apache/conf
  #     - wordpress:/bitnami/wordpress
  #     - ./backups:/usr/share/
  #   depends_on:
  #     - mysql8
  #   networks:
  #     - pwp_net

# volumes:
#   wordpress:
#     driver: local

networks:
  pwp_net:
    name: pwp_net
  ho_apps:
    name: ho_apps
    external: true
