version: "3.6"

services:
  mailhog:
    container_name: mailhog.pedalwithpete
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - ho_apps
      - pwp_net

  adminer:
    container_name: adminer.pedalwithpete
    image: adminer
    ports:
      - 28081:8080
    networks:
      - pwp_net
    depends_on:
      - mysql8

  mysql8:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql8.pedalwithpete
    # Serves as a surrougate trigger for initializing the db: https://hub.docker.com/_/mysql?tab=description#usage-against-an-existing-database
    environment:
      MYSQL_ROOT_PASSWORD: ${PWP_DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql8/db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    networks:
      - pwp_net

  wordpress:
    image: wordpress:6.1-php7.4-apache
    container_name: wp.pedal_with_pete
    environment:
      WORDPRESS_DB_HOST: mysql8.pedalwithpete
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${PWP_DB_PASSWORD}
      WORDPRESS_DB_NAME: PedalWithPete # create new schema with utf8mb4_bin
      WORDPRESS_DEBUG: 1
    restart: unless-stopped
    ports:
      - 28080:80
    volumes:
      - ./app/wordpress:/var/www/html
    depends_on:
      - mysql8
    networks:
      - pwp_net

networks:
  pwp_net:
    name: pwp_net
  ho_apps:
    name: ho_apps
    external: true
