name: Cypress Tests

on: [pull_request, push]

jobs:
  cypress-e2e-chrome:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # Install NPM dependencies
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # PNPM setup github action: https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v2.2.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # and run all Cypress tests
      - name: E2E on Chrome
        # Cypress github action: https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: pnpm test
