# Guard against regressions due to dependency updates
# on Pedal with Pete websites
name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  # Set the default website URL
  WEBSITE_URL: https://pedalwithpete.org

jobs:
  # https://sandboxforpwpwordpress.azurewebsites.net/
  cypress-e2e:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version:
          - "16"
          - "18"
          - "20"
          - "lts/*"
        browser:
          - chrome
          # - firefox
          # - edge

    steps:
      - uses: actions/checkout@v4

      # # https://github.com/pedal-with-pete/e2e-composite-action
      # - uses: pedal-with-pete/e2e-composite-action@v1.0.6

      # Install NPM dependencies
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # PNPM setup github action: https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Check PNPM store path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Check PNPM store path
        shell: bash
        run: |
          echo "STORE_PATH=${{ env.STORE_PATH }}"

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: E2E ${{ matrix.node-version }} / ${{ matrix.browser }} tests
        # Cypress github action: https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v4
        with:
          browser: ${{ matrix.browser }}
          spec: |
            cypress/e2e/1-donate/**/*.cy.js
            cypress/e2e/2-volunteer/**/*.cy.js
