# Guard against regressions due to dependency updates
# on Pedal with Pete websites
name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  # https://sandboxforpwpwordpress.azurewebsites.net/
  cypress-e2e-chrome:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # https://github.com/pedal-with-pete/e2e-composite-action
      - uses: pedal-with-pete/e2e-composite-action@v1.0.6

      - name: E2E on Chrome
        # Cypress github action: https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v4
        env:
          WEBSITE_URL: https://pedalwithpete.org
        with:
          browser: chrome
          spec: |
            cypress/e2e/1-donate/**/*.cy.js
            cypress/e2e/2-volunteer/**/*.cy.js
