# TODO: To repeat these tests for both the sandbox and production
#   review the docs on setting up a composite action: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: Cypress E2E Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # https://sandboxforpwpwordpress.azurewebsites.net/
  cypress-e2e-chrome:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # https://github.com/pedal-with-pete/e2e-composite-action
      - uses: pedal-with-pete/e2e-composite-action@v1.0.3
        with:
          website_url: https://pedalwithpete.org
