# Guard against regressions due to dependency updates
# on Pedal with Pete websites
name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  # https://sandboxforpwpwordpress.azurewebsites.net/
  cypress-e2e-chrome:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # # https://github.com/pedal-with-pete/e2e-composite-action
      # - uses: pedal-with-pete/e2e-composite-action@v1.0.6

      # Install NPM dependencies
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # PNPM setup github action: https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Check PNPM store path
        shell: bash
        run: |
          echo "STORE_PATH=${{ steps.pnpm-cache.outputs.STORE_PATH }}"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: E2E on Chrome
        # Cypress github action: https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v4
        env:
          WEBSITE_URL: https://pedalwithpete.org
        with:
          browser: chrome
          spec: |
            cypress/e2e/1-donate/**/*.cy.js
            cypress/e2e/2-volunteer/**/*.cy.js
